-- Insert 10 agents
INSERT INTO `agent` (`email`, `first_name`, `last_name`, `phone_number`, `language_preference`, `theme_preference`, `password`, `agent_title`, `user_role`) VALUES ('agent1@example.com', 'John', 'Doe', '1234567890', 'en', 'light', '$2a$10$5YzOrGF5wdEAuswP9EtZkeAdv9BVhVqzltizgsiAY6//yGPvskcFO', 'AGENT', 'SALES_AGENT')
INSERT INTO `agent` (`email`, `first_name`, `last_name`, `phone_number`, `language_preference`, `theme_preference`, `password`, `agent_title`, `user_role`) VALUES ('agent2@example.com', 'Jane', 'Smith', '1234567891', 'rs', 'dark', '$2a$10$6D6ZC2Dy1ofpVDgsIzb/NeDx6YBFR1y1QvN96J8tz61Qx2Y.E3/wu', 'BROKER', 'SALES_AGENT')
INSERT INTO `agent` (`email`, `first_name`, `last_name`, `phone_number`, `language_preference`, `theme_preference`, `password`, `agent_title`, `user_role`) VALUES ('agent3@example.com', 'Emily', 'Johnson', '1234567892', 'en', 'light', '$2a$10$279PgoRtan6dC39t0w4fTOHHVT0qvnh3x9W0DfHknGmvwijwQ/Xs.', 'CONSULTANT', 'SALES_AGENT')
INSERT INTO `agent` (`email`, `first_name`, `last_name`, `phone_number`, `language_preference`, `theme_preference`, `password`, `agent_title`, `user_role`) VALUES ('agent4@example.com', 'Michael', 'Brown', '1234567893', 'rs', 'dark', '$2a$10$AMuDton14izwRAW5eFrgAefkCj/Xwqq50o8dq3QR0zUh1V0Y3Gy4W', 'UNDERWRITER', 'SALES_AGENT')
INSERT INTO `agent` (`email`, `first_name`, `last_name`, `phone_number`, `language_preference`, `theme_preference`, `password`, `agent_title`, `user_role`) VALUES ('agent5@example.com', 'Chris', 'Davis', '1234567894', 'en', 'light', '$2a$10$zMJFGUCwxwROK6iGvYiUVuoJfFiEM1yLaBZwKaWxFWU8e9CfeOHyi', 'RISK_MANAGER', 'ADMIN')
INSERT INTO `agent` (`email`, `first_name`, `last_name`, `phone_number`, `language_preference`, `theme_preference`, `password`, `agent_title`, `user_role`) VALUES ('agent6@example.com', 'Jessica', 'Miller', '1234567895', 'rs', 'dark', '$2a$10$fc94Htd9i/MXFtGZOvgWV.srJtLanaF6GtFIP7US8NbIHWo8/nvYK', 'ACCOUNT_EXECUTIVE', 'ADMIN')
INSERT INTO `agent` (`email`, `first_name`, `last_name`, `phone_number`, `language_preference`, `theme_preference`, `password`, `agent_title`, `user_role`) VALUES ('agent7@example.com', 'David', 'Wilson', '1234567896', 'en', 'light', '$2a$10$lKuYZUa0Zd9IPy0jPENepuQIO3m02SIdc/ATBUIUEvHeHH5WMA.WK', 'AGENT', 'SALES_AGENT')
INSERT INTO `agent` (`email`, `first_name`, `last_name`, `phone_number`, `language_preference`, `theme_preference`, `password`, `agent_title`, `user_role`) VALUES ('agent8@example.com', 'Sarah', 'Moore', '1234567897', 'rs', 'dark', '$2a$10$GLGMLg4WJGgu2DPMKLZ/ouE.4sxUy7byIdoWvNpzxq.DSBEfbd8ru', 'BROKER', 'SALES_AGENT')
INSERT INTO `agent` (`email`, `first_name`, `last_name`, `phone_number`, `language_preference`, `theme_preference`, `password`, `agent_title`, `user_role`) VALUES ('agent9@example.com', 'Daniel', 'Taylor', '1234567898', 'en', 'light', '$2a$10$JpjhBsnyAxuJvTlpms/umej/fyvVg7P9J5Hd3zq7skRzWSN2/wE32', 'CONSULTANT', 'SALES_AGENT')
INSERT INTO `agent` (`email`, `first_name`, `last_name`, `phone_number`, `language_preference`, `theme_preference`, `password`, `agent_title`, `user_role`) VALUES ('agent10@example.com', 'Laura', 'Anderson', '1234567899', 'rs', 'dark', '$2a$10$zH.j4U/mAtXbE/CxRCMkVu.WJNcEVy12ZpsI1.gC/DjI59amN4UJG', 'UNDERWRITER', 'SALES_AGENT')

-- Insert 10 requesters
INSERT INTO `requester` (`email`, `first_name`, `last_name`, `phone_number`) VALUES ('requester1@example.com', 'Alice', 'Johnson', '2345678901')
INSERT INTO `requester` (`email`, `first_name`, `last_name`, `phone_number`) VALUES ('requester2@example.com', 'Bob', 'Williams', '2345678902')
INSERT INTO `requester` (`email`, `first_name`, `last_name`, `phone_number`) VALUES ('requester3@example.com', 'Charlie', 'Jones', '2345678903')
INSERT INTO `requester` (`email`, `first_name`, `last_name`, `phone_number`) VALUES ('requester4@example.com', 'Diana', 'Brown', '2345678904')
INSERT INTO `requester` (`email`, `first_name`, `last_name`, `phone_number`) VALUES ('requester5@example.com', 'Edward', 'Davis', '2345678905')
INSERT INTO `requester` (`email`, `first_name`, `last_name`, `phone_number`) VALUES ('requester6@example.com', 'Fiona', 'Martinez', '2345678906')
INSERT INTO `requester` (`email`, `first_name`, `last_name`, `phone_number`) VALUES ('requester7@example.com', 'George', 'Hernandez', '2345678907')
INSERT INTO `requester` (`email`, `first_name`, `last_name`, `phone_number`) VALUES ('requester8@example.com', 'Hannah', 'Lopez', '2345678908')
INSERT INTO `requester` (`email`, `first_name`, `last_name`, `phone_number`) VALUES ('requester9@example.com', 'Isaac', 'Gonzalez', '2345678909')
INSERT INTO `requester` (`email`, `first_name`, `last_name`, `phone_number`) VALUES ('requester10@example.com', 'Jackie', 'Wilson', '2345678910')

-- Insert 20 insurance policies
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-01', 1000.00, 5000.00, 100.00, 1, 1, 'CAR')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-02', 1500.00, 6000.00, 200.00, 2, 2, 'HEALTH')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-03', 2000.00, 7000.00, 300.00, 3, 3, 'HOUSE')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-04', 2500.00, 8000.00, 400.00, 4, 4, 'BUSINESS')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-05', 3000.00, 9000.00, 500.00, 5, 5, 'TRAVEL')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-06', 3500.00, 10000.00, 600.00, 6, 6, 'JEWELRY')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-07', 4000.00, 11000.00, 700.00, 7, 7, 'CAR')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-08', 4500.00, 12000.00, 800.00, 8, 8, 'HEALTH')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-09', 5000.00, 13000.00, 900.00, 9, 9, 'HOUSE')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-10', 5500.00, 14000.00, 1000.00, 10, 10, 'BUSINESS')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-11', 6000.00, 15000.00, 1100.00, 1, 2, 'TRAVEL')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-12', 6500.00, 16000.00, 1200.00, 2, 3, 'JEWELRY')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-13', 7000.00, 17000.00, 1300.00, 3, 4, 'CAR')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-14', 7500.00, 18000.00, 1400.00, 4, 5, 'HEALTH')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-15', 8000.00, 19000.00, 1500.00, 5, 6, 'HOUSE')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-16', 8500.00, 20000.00, 1600.00, 6, 7, 'BUSINESS')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-17', 9000.00, 21000.00, 1700.00, 7, 8, 'TRAVEL')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-18', 9500.00, 22000.00, 1800.00, 8, 9, 'JEWELRY')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-19', 10000.00, 23000.00, 1900.00, 9, 10, 'CAR')
INSERT INTO `insurance_policy` (`date_created`, `estimated_price`, `loss_price_range_max`, `loss_price_range_min`, `agent_id`, `requester_id`, `insurance_item`) VALUES ('2023-01-20', 10500.00, 24000.00, 2000.00, 10, 1, 'HEALTH')

-- Insert 20 insurance policy coverages
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (1, 'BASIC')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (2, 'ADVANCED')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (3, 'BUILDING_INSURANCE')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (4, 'BUSINESS_PROPERTY')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (5, 'CREDIT_RISK')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (6, 'CYBER')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (7, 'FIRE')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (8, 'LANDLORD_INSURANCE')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (9, 'NATURAL_DISASTER')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (10, 'PRIVATE')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (11, 'PUBLIC')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (12, 'SHIPPING')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (13, 'THEFT')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (14, 'TRAFFIC_ACCIDENT')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (15, 'BASIC')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (16, 'ADVANCED')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (17, 'BUILDING_INSURANCE')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (18, 'BUSINESS_PROPERTY')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (19, 'CREDIT_RISK')
INSERT INTO `insurance_policy_coverage` (`insurance_policy_id`, `coverages`) VALUES (20, 'CYBER')